name: 3d-bpp

channels:
  - conda-forge
  - defaults

dependencies:
  - black==21.7b0
  - loguru==0.5.3
  - matplotlib==3.4.2
  - nb_black==1.0.7
  - numpy==1.21.1
  - pandas==1.2.5
  - pip==21.2.1
  - python==3.9.6
  - seaborn==0.11.1
  - tqdm==4.61.2
  - streamlit==0.85.1
  - pip:
      - ortools==8.2.8710
      - rectpack==0.2.1
